version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers: 
      - "sweexordious"
      - "rahulghangas"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers: 
      - "sweexordious"
      - "rahulghangas"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - automerge
      - dependencies
    reviewers: 
      - "sweexordious"
      - "rahulghangas"
