# stage 1 Build qgb binary
FROM golang:1.19-alpine as builder
RUN apk update && apk --no-cache add make gcc musl-dev git
COPY . /orchestrator-relayer
WORKDIR /orchestrator-relayer
RUN make build

# to get the celestia-app binary
FROM ghcr.io/celestiaorg/celestia-app:ff13026 as celestia

# final image
FROM alpine:3.17.2
# hadolint ignore=DL3018
RUN apk update && apk --no-cache add bash

COPY --from=builder /orchestrator-relayer/build/qgb /bin/qgb
COPY --from=celestia /bin/celestia-appd /bin/celestia-appd

# p2p port
EXPOSE 30000

CMD [ "/bin/qgb" ]
